In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.array([2,4,6])

In [5]:
X = np.array([[1,2,3], [4,5,6]])

In [6]:
Y = np.array([[2,4,6], [8,10,12]])

In [7]:
x[2]

3

In [8]:
x[0:2]

array([1, 2])

In [9]:
z = x + y

In [10]:
z

array([3, 6, 9])

In [11]:
X[:, 1]

array([2, 5])

In [12]:
Y[:, 1]

array([ 4, 10])

In [13]:
X[:, 1] + Y[:, 1]

array([ 6, 15])

In [14]:
X[1,:]

array([4, 5, 6])

In [15]:
X[1,:] + Y[1,:]

array([12, 15, 18])

In [16]:
X[1]

array([4, 5, 6])

In [17]:
[2,4] + [6,8]

[2, 4, 6, 8]

In [18]:
np.array([2,4]) + np.array([6,8])

array([ 8, 12])